# Dependabot creates pull requests to keep dependencies secure and up-to-date.
#
# Opt out at any time by removing the .github/dependabot.yml config file.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "./.github/workflows"
    schedule:
      interval: weekly

  - package-ecosystem: "gomod"
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "./docker"
    schedule:
      interval: weekly
