environment: DEV

log:
  outputFile: ".logs/xrf-q2.log"

redis:
  database: 0
  protocol: 2
  poolSize: 5
  password: ""
  maxRetries: 1
  minIdleConns: 2
  dial_timeout: 10s
  read_timeout: 15s
  write_timeout: 30s
  address: "127.0.0.1:6379"

postgres:
  port: 5733
  retries: 2
  ssl_mode: true
  sslMode: true
  user: "postgres"
  host: "localhost"
  read_timeout: 20
  write_timeout: 30
  password: "postgres"
  name: "xrf-q2-pg-bid"

timescaledb:
  port: 5733
  ssl_mode: true
  user: "postgres"
  host: "localhost"
  read_timeout: 20s
  write_timeout: 30s
  connectRetries: 2
  name: xrf-q2-ts-bid
  password: "postgres"
