environment: DEV

log:
  outputFile: ".logs/xrf-q2.log"

redis:
  database: 0
  protocol: 2
  poolSize: 5
  password: ""
  maxRetries: 1
  minIdleConns: 2
  dialTimeout: 10s
  readTimeout: 15s
  writeTimeout: 30s
  address: "127.0.0.1:6379"

postgres:
  port: 5733
  sslMode: true
  readTimeout: 20s
  user: "postgres"
  host: "localhost"
  writeTimeout: 30s
  password: "postgres"
  databaseName: "xrf-q2-pg-bid"

timescaledb:
  port: 5733
  sslMode: true
  user: "postgres"
  readTimeout: 20s
  host: "localhost"
  writeTimeout: 30s
  connectRetries: 2
  password: "postgres"
  databaseName: "xrf-q2-ts-bid"
