environment: DEV

log:
  outputFile: ".logs/xrf-q2.log"

redis:
  database: 0
  protocol: 2
  poolSize: 5
  password: ""
  maxRetries: 1
  minIdleConns: 2
  dial_timeout: 10s
  read_timeout: 15s
  write_timeout: 30s
  address: "127.0.0.1:6379"

postgres:
  port: 5432
  retries: 2
  readTimeout: 20
  user: "postgres"
  writeTimeout: 30
  host: "localhost"
  sslMode: "verify-ca"
  password: "postgres"
  name: "xrf-q2-pg-bid"

timescaledb:
  port: 5432
  readTimeout: 20
  user: "postgres"
  writeTimeout: 30
  host: "localhost"
  connectRetries: 2
  sslMode: "verify-ca"
  password: "postgres"
  databaseName: "xrf-q2-ts-bid"
